# Generated by Django 3.2.5 on 2021-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=122)),
                ('town', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
