# Generated by Django 3.2.5 on 2021-10-09 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_adress_farmer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='product',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
