# Generated by Django 3.2.5 on 2021-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_farmer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='product',
            field=models.CharField(default='', max_length=500),
        ),
    ]
