# Generated by Django 3.2.5 on 2021-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_farmer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('town', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
