# Generated by Django 3.2.5 on 2021-10-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customer_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
