# Generated by Django 3.2.7 on 2021-10-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
